package com.uxplima.uxmessentials.security.application;

import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

import com.uxplima.uxmessentials.security.domain.TwoFactorSecret;

/**
 * The in-memory registry of TOTP secrets that have been generated by {@code /2fa setup} but not yet confirmed with a
 * valid code. A secret is <b>not</b> persisted until the player proves they can generate a code from it: that is
 * what stops a mistyped or never-scanned secret from locking the player out of their own account at the Phase-2 join
 * check. It is transient by design: a pending enrolment that is never confirmed simply evaporates on restart, and
 * the player runs {@code /2fa setup} again.
 *
 * <p>State is owned solely here and mutated only through {@link ConcurrentHashMap} atomics, keyed by player uuid, so
 * two concurrent commands for the same player never interleave a half-write.
 */
public final class PendingTotpEnrollments {

    private final ConcurrentHashMap<UUID, TwoFactorSecret> pending = new ConcurrentHashMap<>();

    /** Record {@code secret} as the player's pending enrolment, replacing any earlier un-confirmed one. */
    public void store(UUID playerId, TwoFactorSecret secret) {
        Objects.requireNonNull(playerId, "playerId");
        Objects.requireNonNull(secret, "secret");
        pending.put(playerId, secret);
    }

    /** The player's pending, un-confirmed secret, if they have one. */
    public Optional<TwoFactorSecret> pending(UUID playerId) {
        Objects.requireNonNull(playerId, "playerId");
        return Optional.ofNullable(pending.get(playerId));
    }

    /** Drop the player's pending enrolment (on confirm, or when they abandon it). */
    public void clear(UUID playerId) {
        Objects.requireNonNull(playerId, "playerId");
        pending.remove(playerId);
    }

    /** Forget every pending enrolment: called on module stop so a disable leaves no residual secret in memory. */
    public void clearAll() {
        pending.clear();
    }
}
