package com.uxplima.uxmessentials.shared.menu;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;

import com.uxplima.uxmessentials.shared.adapter.inbound.gui.menu.binding.MenuBindings;
import com.uxplima.uxmessentials.shared.adapter.inbound.gui.menu.spec.MenuSpec;
import com.uxplima.uxmessentials.shared.adapter.inbound.gui.menu.spec.MenuSpecLoader;
import org.junit.jupiter.api.Test;
import org.spongepowered.configurate.ConfigurationNode;
import org.spongepowered.configurate.hocon.HoconConfigurationLoader;

/**
 * A shipped menu spec may only name binding ids that production wiring actually registers. Without this guard a
 * typo in a {@code .conf} (or a spec that outlives the wiring that fed it) becomes a broken menu a player meets
 * at runtime instead of a failure a maintainer meets at build time. The test walks the bundled specs, parses each
 * (a parse failure is itself a drift the test surfaces), and asserts every ref resolves against an allowlist that
 * mirrors the ids the feature wiring registers.
 *
 * <p>The four {@code EXPECTED_*} sets are the contract: keep them in sync with the ids registered through
 * {@link MenuBindings} in the production wiring. Each migrated menu lands its ids here in the same change that adds
 * the spec and the wiring (warp-sounds and the vault selector are wired today).
 */
class ShippedSpecBindingsDriftTest {

    /** Action ids any shipped spec may reference. Keep in sync with the ids registered in production wiring. */
    private static final Set<String> EXPECTED_ACTIONS = Set.of(
            "trade:confirm",
            "trade:money",
            "trade:money-cycle",
            "trade:experience",
            "trade:cross-confirm",
            "warp:set-sound",
            "warp:custom-sound",
            "warp:remove-sound",
            "warp:edit-back",
            "vault:open-slot",
            "communication:chat-lock",
            "communication:clearchat",
            "communication:broadcast",
            "communication:open-announcer",
            "communication:close",
            "messaging:unignore",
            "messaging:ignore-add",
            "messaging:read-mail",
            "messaging:clear-mail",
            "messaging:mail-back",
            "ranks:rankup",
            "close",
            "sound",
            "list-sort",
            "list-filter",
            "list-search",
            "itemworld:open-workbench",
            "itemworld:open-anvil",
            "itemworld:open-cartography",
            "itemworld:open-grindstone",
            "itemworld:open-loom",
            "itemworld:open-smithingtable",
            "itemworld:open-stonecutter",
            "itemworld:open-enderchest",
            "itemworld:time-day",
            "itemworld:time-night",
            "itemworld:weather-clear",
            "itemworld:weather-rain",
            "itemworld:clear-drops",
            "itemworld:clear-mobs",
            "itemedit:rename",
            "itemedit:reset-name",
            "itemedit:lore-add",
            "itemedit:lore-remove",
            "itemedit:lore-clear",
            "itemedit:enchant-add",
            "itemedit:enchant-remove",
            "itemedit:flags",
            "itemedit:unbreakable",
            "itemedit:model-set",
            "itemedit:model-clear",
            "itemedit:durability",
            "itemedit:repair",
            "security:pin-0",
            "security:pin-1",
            "security:pin-2",
            "security:pin-3",
            "security:pin-4",
            "security:pin-5",
            "security:pin-6",
            "security:pin-7",
            "security:pin-8",
            "security:pin-9",
            "security:pin-clear",
            "security:pin-submit",
            "security:pin-totp",
            "staff:teleport-to",
            "staff:examine",
            "teleport:rtp-world",
            "holograms:edit",
            "holograms:create",
            "playerwarps:edit",
            "playerwarps:create",
            "playerwarps:browse-click",
            "playerwarps:browse-teleport",
            "pwarp-teleport",
            "pwarp-rate",
            "playerwarps:view-favourite",
            "playerwarps:view-unfavourite",
            "playerwarps:view-rate",
            "playerwarps:view-manage",
            "playerwarps:view-back",
            "playerwarps:rate-back",
            "pwarp-rename",
            "pwarp-displayname",
            "pwarp-description",
            "pwarp-category",
            "pwarp-price",
            "pwarp-password",
            "pwarp-transfer",
            "pwarp-sponsor",
            "playerwarps:manage-icon",
            "playerwarps:manage-access",
            "playerwarps:manage-clearpw",
            "playerwarps:manage-move",
            "playerwarps:manage-withdraw",
            "playerwarps:manage-delete",
            "playerwarps:manage-back",
            "playerwarps:manage-members",
            "playerwarps:manage-whitelist",
            "playerwarps:manage-bans",
            "playerwarps:members-remove",
            "playerwarps:whitelist-remove",
            "playerwarps:bans-remove",
            "pwarp-mem-addco",
            "pwarp-mem-addmgr",
            "pwarp-wl-add",
            "pwarp-ban-add",
            "playerwarps:people-back",
            "playerwarps:browse-all",
            "playerwarps:browse-mine",
            "playerwarps:browse-favourites",
            "playerwarps:browse-top",
            "playerwarps:category-open",
            "picker:pick",
            "picker:offline",
            "picker:footer-one",
            "picker:footer-two",
            "economy:currency-pick",
            "vote:site-open",
            "kits:category-assign",
            "kits:category-clear",
            "kits:category-back",
            "kits:category-parent-assign",
            "kits:category-parent-clear",
            "kits:category-parent-back",
            "kits:category-manager-open",
            "kits:category-manager-create",
            "kits:category-manager-back",
            "warps:category-assign",
            "warps:category-clear",
            "warps:category-back",
            "warps:category-parent-assign",
            "warps:category-parent-clear",
            "warps:category-parent-back",
            "warps:category-manager-open",
            "warps:category-manager-create",
            "warps:category-manager-back",
            "playerwarps:open-categories",
            "playerwarps:sponsor-open",
            "playerwarps:icon-set",
            "playerwarps:icon-reset",
            "playerwarps:icon-back",
            "input",
            "confirm",
            "npc:edit",
            "npc:create",
            "worlds:edit",
            "worlds:teleport",
            "worlds:create",
            "worlds:editor-rules",
            "worlds:editor-access",
            "worlds:editor-generation",
            "worlds:editor-main-back",
            "worlds:editor-toggle-load",
            "worlds:editor-generation-back",
            "worlds:create-name",
            "worlds:create-seed",
            "worlds:create-environment-next",
            "worlds:create-environment-prev",
            "worlds:create-type-next",
            "worlds:create-type-prev",
            "worlds:create-generator-next",
            "worlds:create-generator-prev",
            "worlds:create-confirm",
            "worlds:create-back",
            "worlds:grid-cycle-next",
            "worlds:grid-cycle-prev",
            "worlds:grid-cycle-clear",
            "worlds:grid-back",
            "homes:set-icon",
            "homes:reset-icon",
            "homes:icon-back",
            "homes:uninvite",
            "homes:invite-add",
            "homes:invites-back",
            "homes:teleport",
            "homes:delete",
            "homes:relocate",
            "homes:rename",
            "homes:open-icons",
            "homes:toggle-visibility",
            "homes:open-invites",
            "homes:action-back",
            "homes:open-slot",
            "moderation:open-detail",
            "moderation:release",
            "moderation:jail-reanchor",
            "moderation:jail-goto",
            "moderation:jail-delete",
            "moderation:jail-back",
            "moderation:punish-apply",
            "moderation:punish-apply-silent",
            "moderation:set-reason",
            "moderation:punish-back",
            "kits:manager-edit",
            "kits:manager-create",
            "kits:manager-categories",
            "kits:cat-set-name",
            "kits:cat-set-material",
            "kits:cat-set-lore",
            "kits:cat-set-slot",
            "kits:cat-set-parent",
            "kits:cat-set-delete",
            "kits:cat-set-back",
            "kits:settings-edit-items",
            "kits:settings-permission",
            "kits:settings-onetime",
            "kits:settings-cooldown",
            "kits:settings-cost",
            "kits:settings-display-name",
            "kits:settings-display-material",
            "kits:settings-display-lore",
            "kits:settings-commands",
            "kits:settings-firstjoin",
            "kits:settings-autoequip",
            "kits:settings-delete",
            "kits:settings-category",
            "kits:settings-back",
            "kits:browse-click",
            "kits:browse-back",
            "warps:manager-edit",
            "warps:manager-create",
            "warps:manager-categories",
            "warps:cat-set-name",
            "warps:cat-set-material",
            "warps:cat-set-lore",
            "warps:cat-set-slot",
            "warps:cat-set-parent",
            "warps:cat-set-delete",
            "warps:cat-set-back",
            "warps:browse-click",
            "warps:browse-back",
            "warps:editor-teleport",
            "warps:editor-icon-set",
            "warps:editor-icon-clear",
            "warps:editor-category",
            "warps:editor-lock",
            "warps:editor-password-set",
            "warps:editor-password-clear",
            "warps:editor-welcome",
            "warps:editor-sounds-departure",
            "warps:editor-sounds-arrival",
            "warps:editor-sounds-clear",
            "warps:editor-particles-departure",
            "warps:editor-particles-arrival",
            "warps:editor-particles-clear",
            "warps:editor-warmup-set",
            "warps:editor-warmup-clear",
            "warps:editor-cooldown-set",
            "warps:editor-cooldown-clear",
            "warps:editor-close",
            "warps:welcome-edit",
            "warps:welcome-remove",
            "warps:welcome-cycle",
            "warps:welcome-add",
            "warps:welcome-clear",
            "warps:welcome-back",
            "economy:open-bank",
            "economy:create-bank",
            "economy:remove-member",
            "economy:add-member",
            "economy:bank-back",
            "economy:bank-deposit",
            "economy:bank-deposit-withdraw",
            "economy:bank-members",
            "economy:bank-logs",
            "economy:bank-actions-back",
            "economy:open-history",
            "economy:pay-confirm",
            "economy:pay-cancel",
            "economy:target-give",
            "economy:target-take",
            "economy:target-set",
            "economy:target-reset",
            "economy:target-history",
            "economy:target-select-currency",
            "economy:target-back",
            "economy:bulk-giveall",
            "economy:bulk-resetall",
            "economy:bulk-select-currency",
            "economy:bulk-back",
            "economy:admin-manage",
            "economy:admin-bulk",
            "economy:admin-history",
            "economy:loan-entry",
            "economy:loan-request",
            "economy:exchange-source",
            "economy:exchange-target",
            "economy:exchange-convert",
            "invrollback:teleport",
            "invrollback:restore",
            "invrollback:export",
            "villagers:toggle-trading",
            "villagers:remove-1",
            "villagers:remove-2",
            "villagers:remove-3",
            "villagers:remove-4",
            "villagers:remove-5");

    /** Condition ids any shipped spec may reference. Keep in sync with the ids registered in production wiring. */
    private static final Set<String> EXPECTED_CONDITIONS = Set.of(
            "trade:money-enabled",
            "trade:confirmed",
            "trade:awaiting",
            "trade:partner-confirmed",
            "trade:partner-awaiting",
            "perm",
            "has-prev",
            "has-next",
            "expr",
            "picker:has-footer-one",
            "picker:has-footer-two",
            "security:totp-enabled",
            "homes:home-public",
            "homes:home-private",
            "playerwarps:no-password",
            "playerwarps:password-required",
            "playerwarps:not-favourited",
            "playerwarps:favourited",
            "playerwarps:not-owner",
            "playerwarps:viewer-member",
            "pwarp-viewer-can",
            "playerwarps:manage-sponsor",
            "moderation:confirm-silent-offered",
            "economy:can-add-member",
            "economy:multi-currency",
            "economy:exchange-has-rate",
            "economy:exchange-no-rate",
            "warps:browse-has-parent",
            "warps:editor-server-warp",
            "kits:browse-has-parent",
            "villagers:trading-enabled",
            "villagers:trading-disabled");

    /** Placeholder ids any shipped spec may reference. Keep in sync with the ids registered in production wiring. */
    private static final Set<String> EXPECTED_PLACEHOLDERS = Set.of(
            "trade_title",
            "trade_cross_title",
            "trade_money_name",
            "trade_money_lore",
            "trade_experience_lore",
            "trade_partner_money_lore",
            "trade_partner_experience_lore",
            "invsee_title",
            "invrollback_preview_title",
            "invrollback_info_lore",
            "villagers_manager_title",
            "endersee_title",
            "sound",
            "sound_material",
            "vault_icon",
            "vault_name",
            "vault_lore",
            "communication_lock_state",
            "announcement_id",
            "announcement_lines",
            "announcement_channels",
            "ignore_target",
            "mail_icon",
            "mail_sender",
            "mail_time",
            "mail_snippet",
            "mail_message",
            "recipe_slot0_material",
            "recipe_slot0_name",
            "recipe_slot0_lore",
            "recipe_slot1_material",
            "recipe_slot1_name",
            "recipe_slot1_lore",
            "recipe_slot2_material",
            "recipe_slot2_name",
            "recipe_slot2_lore",
            "recipe_slot3_material",
            "recipe_slot3_name",
            "recipe_slot3_lore",
            "recipe_slot4_material",
            "recipe_slot4_name",
            "recipe_slot4_lore",
            "recipe_slot5_material",
            "recipe_slot5_name",
            "recipe_slot5_lore",
            "recipe_slot6_material",
            "recipe_slot6_name",
            "recipe_slot6_lore",
            "recipe_slot7_material",
            "recipe_slot7_name",
            "recipe_slot7_lore",
            "recipe_slot8_material",
            "recipe_slot8_name",
            "recipe_slot8_lore",
            "recipe_result_material",
            "recipe_result_name",
            "recipe_result_lore",
            "entity_icon",
            "entity_type",
            "entity_count",
            "entity_radius",
            "itemedit_preview",
            "itemedit_preview_name",
            "itemedit_preview_lore",
            "security_keypad_entry",
            "security_keypad_digit_0",
            "security_keypad_digit_1",
            "security_keypad_digit_2",
            "security_keypad_digit_3",
            "security_keypad_digit_4",
            "security_keypad_digit_5",
            "security_keypad_digit_6",
            "security_keypad_digit_7",
            "security_keypad_digit_8",
            "security_keypad_digit_9",
            "iw_station_workbench",
            "iw_station_anvil",
            "iw_station_cartography",
            "iw_station_grindstone",
            "iw_station_loom",
            "iw_station_smithingtable",
            "iw_station_stonecutter",
            "iw_station_enderchest",
            "staff_player_name",
            "rtp_world_icon",
            "rtp_world_name",
            "hologram_name",
            "hologram_lines",
            "hologram_world",
            "hologram_x",
            "hologram_y",
            "hologram_z",
            "pwarp_icon",
            "pwarp_name",
            "pwarp_owner",
            "pwarp_world",
            "pwarp_x",
            "pwarp_y",
            "pwarp_z",
            "pwarp_visibility",
            "pwarp_browse_icon",
            "pwarp_browse_name",
            "pwarp_browse_lore",
            "pwarp_view_name",
            "pwarp_view_lore",
            "pwarp_manage_name",
            "pwarp_manage_lore",
            "picker_title_key",
            "picker_head_icon",
            "picker_head_name",
            "picker_head_lore",
            "picker_footer_one_icon",
            "picker_footer_one_name",
            "picker_footer_one_lore",
            "picker_footer_two_icon",
            "picker_footer_two_name",
            "picker_footer_two_lore",
            "currency_picker_icon",
            "currency_picker_name",
            "currency_picker_lore",
            "currency_picker_active",
            "vote_site_icon",
            "vote_site_name",
            "vote_site_lore",
            "kit_category_icon",
            "kit_category_name",
            "kit_category_lore",
            "kit_parent_icon",
            "kit_parent_name",
            "kit_parent_lore",
            "kit_manager_category_icon",
            "kit_manager_category_name",
            "kit_manager_category_lore",
            "warp_category_icon",
            "warp_category_name",
            "warp_category_lore",
            "warp_parent_icon",
            "warp_parent_name",
            "warp_parent_lore",
            "warp_manager_category_icon",
            "warp_manager_category_name",
            "warp_manager_category_lore",
            "pwarp_category_icon",
            "pwarp_category_name",
            "pwarp_sponsor_icon",
            "pwarp_sponsor_name",
            "pwarp_sponsor_owner",
            "pwarp_icon_material",
            "pwarp_people_name",
            "pwarp_member_role",
            "pwarp_ban_reason",
            "pwarp_ban_until",
            "npc_icon",
            "npc_name",
            "npc_type",
            "npc_world",
            "npc_x",
            "npc_y",
            "npc_z",
            "world_icon",
            "world_name",
            "world_environment",
            "world_loaded",
            "world_main_name",
            "world_main_environment",
            "world_main_type",
            "world_main_loaded",
            "world_main_players",
            "world_main_alias",
            "world_main_toggle_material",
            "world_main_toggle_key",
            "world_create_name",
            "world_create_environment",
            "world_create_type",
            "world_create_generator",
            "world_create_seed",
            "world_gen_world",
            "world_gen_environment",
            "world_gen_type",
            "world_gen_seed",
            "world_gen_generator",
            "world_grid_world",
            "world_grid_title_key",
            "world_grid_material",
            "world_grid_label_key",
            "world_grid_value",
            "home_icon_name",
            "invited_player",
            "invited_player_lore",
            "home_name",
            "home_world",
            "home_x",
            "home_y",
            "home_z",
            "home_created",
            "home_icon",
            "home_cell_name",
            "home_cell_lore",
            "mod_active_icon",
            "mod_active_player",
            "mod_active_type",
            "mod_active_issuer",
            "mod_active_reason",
            "mod_active_remaining",
            "mod_history_icon",
            "mod_history_action",
            "mod_history_issuer",
            "mod_history_reason",
            "mod_history_at",
            "mod_jailed_player",
            "mod_jailed_jail",
            "mod_jailed_issuer",
            "mod_jailed_reason",
            "mod_jailed_remaining",
            "mod_jail_edit_jail",
            "mod_jail_edit_coords",
            "mod_confirm_title_key",
            "mod_confirm_player",
            "mod_confirm_apply_label_key",
            "mod_confirm_apply_lore_key",
            "mod_confirm_silent_label_key",
            "mod_confirm_silent_lore_key",
            "mod_confirm_reason",
            "mod_confirm_reason_lore_key",
            "kit_manager_icon",
            "kit_manager_name",
            "kit_manager_seconds",
            "kit_manager_cost",
            "kit_manager_permission",
            "kit_manager_onetime",
            "kit_manager_firstjoin",
            "kit_manager_autoequip",
            "cat_set_id",
            "cat_set_name",
            "cat_set_material",
            "cat_set_lore_count",
            "cat_set_slot",
            "cat_set_parent",
            "warp_cat_set_id",
            "warp_cat_set_name",
            "warp_cat_set_material",
            "warp_cat_set_lore_count",
            "warp_cat_set_slot",
            "warp_cat_set_parent",
            "warp_edit_name",
            "warp_edit_icon_material",
            "warp_edit_icon",
            "warp_edit_lock",
            "warp_edit_password",
            "warp_edit_welcome",
            "warp_edit_welcome_type",
            "warp_edit_sound_departure",
            "warp_edit_sound_arrival",
            "warp_edit_particle_departure",
            "warp_edit_particle_arrival",
            "warp_edit_warmup",
            "warp_edit_cooldown",
            "warp_edit_category",
            "warp_edit_world",
            "warp_edit_x",
            "warp_edit_y",
            "warp_edit_z",
            "warp_welcome_material",
            "warp_welcome_index",
            "warp_welcome_text",
            "warp_welcome_type",
            "kit_set_id",
            "kit_set_perm_material",
            "kit_set_permission",
            "kit_set_onetime",
            "kit_set_cooldown",
            "kit_set_cost",
            "kit_set_display_name",
            "kit_set_display_material",
            "kit_set_display_material_icon",
            "kit_set_display_lore_count",
            "kit_set_commands_count",
            "kit_set_firstjoin",
            "kit_set_autoequip",
            "kit_set_category",
            "warp_manager_icon",
            "warp_manager_name",
            "warp_manager_category",
            "warp_manager_world",
            "warp_manager_x",
            "warp_manager_y",
            "warp_manager_z",
            "warp_browse_icon",
            "warp_browse_name",
            "warp_browse_lore",
            "kit_browse_icon",
            "kit_browse_name",
            "kit_browse_lore",
            "baltop_currency",
            "baltop_rank",
            "baltop_player",
            "baltop_amount",
            "history_title_key",
            "history_player",
            "history_bank",
            "history_icon",
            "history_type_key",
            "history_id",
            "history_date",
            "history_from",
            "history_to",
            "history_amount",
            "history_reason",
            "bank_name",
            "bank_id",
            "bank_balance",
            "bank_creator",
            "bank_members",
            "bank_members_title",
            "bank_member",
            "bank_member_role",
            "wallet_balance",
            "wallet_banknotes",
            "bank_actions_name",
            "payconfirm_target",
            "payconfirm_amount",
            "eco_target",
            "eco_currency",
            "eco_target_balances",
            "loan_profile_name",
            "loan_profile_lore",
            "loan_entry_icon",
            "loan_entry_name",
            "loan_entry_lore",
            "exchange_source_material",
            "exchange_target_material",
            "exchange_source_currency",
            "exchange_target_currency",
            "exchange_source_balance",
            "exchange_target_balance",
            "exchange_rate",
            "exchange_fee");

    /** List-source ids any shipped spec may reference. Keep in sync with the ids registered in production wiring. */
    private static final Set<String> EXPECTED_LISTS = Set.of(
            "warp:sound-options",
            "vault:slots",
            "communication:announcements",
            "messaging:ignores",
            "messaging:mail",
            "playerwarps:people",
            "playerwarps:categories",
            "playerwarps:sponsors",
            "playerwarps:icon-palette",
            "itemworld:entity-tally",
            "staff:players",
            "teleport:rtp-worlds",
            "holograms:list",
            "playerwarps:list",
            "npc:list",
            "worlds:list",
            "worlds:grid",
            "homes:icon-palette",
            "homes:invited-players",
            "home:slots",
            "moderation:active",
            "moderation:history",
            "moderation:jailed",
            "kits:manager",
            "kits:browse",
            "warps:manager",
            "picker:players",
            "economy:currency-picker",
            "vote:sites",
            "kits:category-selector",
            "kits:category-parent-selector",
            "kits:category-manager",
            "warps:category-selector",
            "warps:category-parent-selector",
            "warps:category-manager",
            "warps:browse",
            "warps:welcome",
            "economy:baltop",
            "economy:transactions",
            "economy:banks",
            "economy:bank-members",
            "economy:loan-list");

    /**
     * Paged list-source ids any shipped spec may reference. Registered through {@code pagedList} rather than
     * {@code list}, because a paged source is the one kind that may carry {@code page-size} and {@code sorts} on its
     * list block: the browse menu declares sorts, so validating it as a plain list would wrongly flag those knobs.
     * Keep in sync with the ids registered as paged sources in production wiring.
     */
    private static final Set<String> EXPECTED_PAGED_LISTS = Set.of("playerwarps:browse");

    /**
     * Content-region ids any shipped spec may hand a block of slots to. A region whose provider is not registered
     * would open a hole into a live inventory, so the same allowlist discipline applies as to the other four.
     */
    private static final Set<String> EXPECTED_CONTENTS = Set.of(
            "trade:offer",
            "trade:mirror",
            "trade:cross-offer",
            "playerstate:invsee",
            "playerstate:endersee",
            "invrollback:snapshot",
            "villagers:trades");

    @Test
    void everyShippedSpecReferencesOnlyKnownBindingIds() {
        Path modulesDir = repoRoot().resolve("bukkit-adapter/src/main/resources/modules");
        if (!Files.isDirectory(modulesDir)) {
            return;
        }

        List<MenuSpec> specs = loadAll(modulesDir);

        MenuBindings bindings = new MenuBindings();
        EXPECTED_ACTIONS.forEach(id -> bindings.action(id, ctx -> {}));
        EXPECTED_CONDITIONS.forEach(id -> bindings.condition(id, (ctx, args) -> true));
        EXPECTED_PLACEHOLDERS.forEach(id -> bindings.placeholder(id, ctx -> ""));
        EXPECTED_LISTS.forEach(id -> bindings.list(id, ctx -> List.of()));
        EXPECTED_PAGED_LISTS.forEach(id -> bindings.pagedList(
                id,
                (ctx, request) ->
                        com.uxplima.uxmessentials.shared.adapter.inbound.gui.menu.eval.PagedResult.of(List.of(), 0)));
        EXPECTED_CONTENTS.forEach(id -> bindings.content(id, (ctx, region) -> List.of()));

        assertThat(bindings.validate(specs))
                .as("shipped menu specs reference binding ids not registered in production wiring; register them "
                        + "in the feature wiring (and add them to the matching EXPECTED_* set here), or fix "
                        + "the spec")
                .isEmpty();
    }

    /**
     * Parses every engine spec shipped under a module's {@code gui/} folder; a parse failure propagates as the
     * drift it is. Each built-in menu's spec lives under its own module ({@code modules/<module>/gui/<name>.conf}),
     * alongside the layout {@code .conf}s the older menus still read. An engine spec is told apart by its
     * {@code items} block, a layout conf carries none, so the geometry layouts are skipped rather than parsed as
     * specs.
     */
    private static List<MenuSpec> loadAll(Path modulesDir) {
        MenuSpecLoader loader = new MenuSpecLoader();
        List<MenuSpec> specs = new ArrayList<>();
        try (Stream<Path> walk = Files.walk(modulesDir)) {
            walk.filter(Files::isRegularFile)
                    .filter(p -> p.getFileName().toString().endsWith(".conf"))
                    .filter(ShippedSpecBindingsDriftTest::inGuiFolder)
                    .filter(ShippedSpecBindingsDriftTest::isEngineSpec)
                    .sorted()
                    .forEach(p -> specs.add(loader.load(p)));
        } catch (IOException failure) {
            throw new UncheckedIOException(failure);
        }
        return specs;
    }

    /** True when {@code conf} sits directly in a {@code gui/} folder, where every built-in menu spec now lives. */
    private static boolean inGuiFolder(Path conf) {
        Path parent = conf.getParent();
        return parent != null && parent.getFileName().toString().equals("gui");
    }

    /** True when {@code conf} is an engine menu spec: it declares an {@code items} block; a layout conf does not. */
    private static boolean isEngineSpec(Path conf) {
        try {
            ConfigurationNode root =
                    HoconConfigurationLoader.builder().path(conf).build().load();
            return !root.node("items").virtual();
        } catch (IOException failure) {
            throw new UncheckedIOException(failure);
        }
    }

    private static Path repoRoot() {
        Path dir = Path.of("").toAbsolutePath();
        while (dir != null) {
            if (Files.exists(dir.resolve("settings.gradle.kts"))) {
                return dir;
            }
            dir = dir.getParent();
        }
        throw new IllegalStateException("could not locate the repo root (settings.gradle.kts)");
    }
}
