plugins {
    id("uxmessentials.java-conventions")
    alias(libs.plugins.shadow)
}

// The optional proxy-side cross-server bus broker. It depends on :core only for the pure
// NetworkMessage hierarchy + codec it shares with the bukkit-side bus client (a single pure-codec
// shared by both ends); it compiles against velocity-api ONLY, no paper/bukkit, and ships as a separate jar.

dependencies {
    implementation(project(":core"))
    api(project(":api"))
    compileOnly(libs.velocity.api)
    // Command-control reuses the pure :core domain, reads its config with Configurate HOCON, renders
    // deny/spam text with MiniMessage, and resolves groups via LuckPerms. All three are provided by the
    // Velocity proxy at runtime, so they are compileOnly here and are never shaded into the jar.
    compileOnly(libs.bundles.configs)
    compileOnly(libs.bundles.adventure)
    compileOnly(libs.luckperms.api)
    // The @Plugin annotation processor also emits a velocity-plugin.json. We ship a hand-written
    // descriptor instead (expanded with the project version by processResources below), the single
    // source of truth Velocity loads, so the processor output is suppressed to avoid a duplicate entry.
    annotationProcessor(libs.velocity.api)

    testImplementation(libs.velocity.api) // the broker test mocks ProxyServer / ServerConnection
    // The command-control tests build real Brigadier command trees, parse HOCON, and render MiniMessage.
    testImplementation(libs.bundles.configs)
    testImplementation(libs.bundles.adventure)
}

// The velocity-api annotation processor generates its own velocity-plugin.json from the @Plugin
// annotation; our hand-written resource is authoritative, so drop the generated copy before it reaches
// the jar (keeping the processor on the classpath for its descriptor validation).
tasks.named<JavaCompile>("compileJava") {
    doLast {
        val generated = destinationDirectory.file("velocity-plugin.json").get().asFile
        if (generated.exists()) {
            generated.delete()
        }
    }
}

// Generate BuildConstants so the @Plugin(version = ...) annotation can reference a compile-time
// constant; the same project.version is expanded into velocity-plugin.json below.
val generatedSources = layout.buildDirectory.dir("generated/sources/buildconstants/java/main")

val generateBuildConstants by tasks.registering {
    val outputDir = generatedSources
    val pluginVersion = project.version.toString()
    inputs.property("version", pluginVersion)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = outputDir.get().dir("com/uxplima/uxmessentials/velocity").asFile
        pkgDir.mkdirs()
        pkgDir.resolve("BuildConstants.java").writeText(
            """
            package com.uxplima.uxmessentials.velocity;

            /** Build-time constants surfaced to the {@code @Plugin} descriptor; generated by Gradle. */
            final class BuildConstants {

                /** The plugin version, expanded from the Gradle project version at build time. */
                static final String VERSION = "$pluginVersion";

                private BuildConstants() {}
            }
            """.trimIndent() + "\n",
        )
    }
}

sourceSets {
    main {
        java {
            // Wiring the source dir to the task lets Gradle infer the dependency for every consumer
            // (compileJava, sourcesJar, spotless) so none reads the generated file before it is written.
            srcDir(generateBuildConstants)
        }
    }
}

tasks.processResources {
    val props = mapOf("version" to project.version)
    inputs.properties(props)
    filesMatching("velocity-plugin.json") { expand(props) }
}

tasks.shadowJar { archiveBaseName.set("uxmEssentials-velocity") }

spotless {
    java {
        targetExclude("build/generated-src/**", "build/generated/**")
    }
}
